$wallpaper = /home/n0ctanedev/Pictures/wallpaper.png
$image = /home/n0ctanedev/Pictures/wallpaper.png

$background = rgba(111319ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3036ff)

$inverse_primary = rgba(285cafff)

$inverse_surface = rgba(e2e2e9ff)

$on_background = rgba(e2e2e9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(002e69ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(001a41ff)

$on_primary_fixed_variant = rgba(004493ff)

$on_secondary = rgba(20304fff)

$on_secondary_container = rgba(dae4ffff)

$on_secondary_fixed = rgba(091b39ff)

$on_secondary_fixed_variant = rgba(374767ff)

$on_surface = rgba(e2e2e9ff)

$on_surface_variant = rgba(c3c6d3ff)

$on_tertiary = rgba(510f62ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(340042ff)

$on_tertiary_fixed_variant = rgba(6b2b7aff)

$outline = rgba(8d909dff)

$outline_variant = rgba(434751ff)

$primary = rgba(adc6ffff)

$primary_container = rgba(3365b8ff)

$primary_fixed = rgba(d8e2ffff)

$primary_fixed_dim = rgba(adc6ffff)

$scrim = rgba(000000ff)

$secondary = rgba(b6c6edff)

$secondary_container = rgba(394969ff)

$secondary_fixed = rgba(d8e2ffff)

$secondary_fixed_dim = rgba(b6c6edff)

$shadow = rgba(000000ff)

$source_color = rgba(3365b8ff)

$surface = rgba(111319ff)

$surface_bright = rgba(37393fff)

$surface_container = rgba(1d2025ff)

$surface_container_high = rgba(282a30ff)

$surface_container_highest = rgba(33353aff)

$surface_container_low = rgba(191b21ff)

$surface_container_lowest = rgba(0c0e13ff)

$surface_dim = rgba(111319ff)

$surface_tint = rgba(adc6ffff)

$surface_variant = rgba(434751ff)

$tertiary = rgba(f4aeffff)

$tertiary_container = rgba(8f4c9dff)

$tertiary_fixed = rgba(fdd6ffff)

$tertiary_fixed_dim = rgba(f4aeffff)

