#     █████  ██    ██ ████████  ██████  ███████ ████████  █████  ██████  ████████ 
#    ██   ██ ██    ██    ██    ██    ██ ██         ██    ██   ██ ██   ██    ██    
#    ███████ ██    ██    ██    ██    ██ ███████    ██    ███████ ██████     ██    
#    ██   ██ ██    ██    ██    ██    ██      ██    ██    ██   ██ ██   ██    ██    
#    ██   ██  ██████     ██     ██████  ███████    ██    ██   ██ ██   ██    ██    
#                                                                                 
         

# here, use "uwsm app -- <app_name>" to open a app with some rulesets, like in a workspace
# else use "runapp <app_name>" if no ruleset is needed... it is faster
exec-once = n0ctl-wallSwitch ~/Pictures/wallpaper.png
exec-once = n0ctbar
exec-once = n0ctl-cmd-connectivity-unblock
exec-once = [workspace 1 silent] uwsm app -- firefox
exec-once = [workspace 2 silent] uwsm app -- zeditor
#exec-once = [workspace 3 silent] uwsm app -- github-desktop-plus
#exec-once = [workspace 10 silent] uwsm app -- discord
exec-once = runapp wl-paste --watch clipvault store

exec-once = /usr/lib/polkit-kde-authentication-agent-1
# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
