#    ██     ██ ██ ███    ██     ██████  ██    ██ ██      ███████ ███████ 
#    ██     ██ ██ ████   ██     ██   ██ ██    ██ ██      ██      ██      
#    ██  █  ██ ██ ██ ██  ██     ██████  ██    ██ ██      █████   ███████ 
#    ██ ███ ██ ██ ██  ██ ██     ██   ██ ██    ██ ██      ██           ██ 
#     ███ ███  ██ ██   ████     ██   ██  ██████  ███████ ███████ ███████ 
#                                                                        


#############################################
# IDK WHAT THESE DO, I JUST ADDED THEM
#############################################
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    
    suppress_event = maximize
}
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    
    no_focus = true
}
# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    
    match:class = hyprland-run
    
    move = 20 monitor_h-120
    float = yes
}


#############################################
### HERE COMES THE CUSTOM WINDOW RULES ######
#############################################

# === ============== === #
# ===    TUI APPS    === #
# === ============== === #
windowrule = match:class tui-float,float on  # Float the window
windowrule = match:class tui-float, size 800 400  # Set size
windowrule = match:class tui-float,center on  # Center it

# === ================== === #
# ===    SMILE(emoji)    === #
# === ================== === #
windowrule = match:initial_title Smile,float on  # Float the window
windowrule = match:initial_title Smile, size 800 400  # Set size
windowrule = match:initial_title Smile,center on  # Center it