# Hellpaper Hellwal template config
[Theme]
bg = 1, 4, 16, 255
idle = 159, 54, 248, 255
hover = 255, 198, 255, 255
border = 255, 255, 255, 255
ripple = 175, 136, 255, 255
text = 249, 101, 197, 255

[Settings]
base_thumb_size = 120
base_padding = 10
anim_speed = 20.0
particle_count = 100
max_fps = 200

[Effects]
# Valid effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = blur
keypress_effect = none
exit_effect = glitch
