$background = rgb(010410)
$foreground = rgb(ffc6ff)

$color0 = rgb(010410)
$color1 = rgb(9f36f8)
$color2 = rgb(a33aff)
$color3 = rgb(ff37d8)
$color4 = rgb(af88ff)
$color5 = rgb(9f98ff)
$color6 = rgb(ff90fd)
$color7 = rgb(ffffff)
$color8 = rgb(061143)
$color9 = rgb(7d51a4)
$color10 = rgb(8457b7)
$color11 = rgb(be529b)
$color12 = rgb(8f70ed)
$color13 = rgb(8480f4)
$color14 = rgb(f965c5)
$color15 = rgb(ffc6ff)
