$wallpaper = /home/n0ctanedev/Wallpaper-Bank/wallpapers/Comets-of-that-night.jpg
$image = /home/n0ctanedev/Wallpaper-Bank/wallpapers/Comets-of-that-night.jpg

$background = rgba(101417ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3135ff)

$inverse_primary = rgba(04639bff)

$inverse_surface = rgba(e1e2e8ff)

$on_background = rgba(e1e2e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003354ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(001d33ff)

$on_primary_fixed_variant = rgba(004a77ff)

$on_secondary = rgba(1a3248ff)

$on_secondary_container = rgba(d1e6ffff)

$on_secondary_fixed = rgba(021d32ff)

$on_secondary_fixed_variant = rgba(32495fff)

$on_surface = rgba(e1e2e8ff)

$on_surface_variant = rgba(c0c7d1ff)

$on_tertiary = rgba(4b1a5dff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(320046ff)

$on_tertiary_fixed_variant = rgba(633276ff)

$outline = rgba(8a919bff)

$outline_variant = rgba(414750ff)

$primary = rgba(97cbffff)

$primary_container = rgba(196ba4ff)

$primary_fixed = rgba(cee5ffff)

$primary_fixed_dim = rgba(97cbffff)

$scrim = rgba(000000ff)

$secondary = rgba(b1c9e4ff)

$secondary_container = rgba(344b62ff)

$secondary_fixed = rgba(cee5ffff)

$secondary_fixed_dim = rgba(b1c9e4ff)

$shadow = rgba(000000ff)

$source_color = rgba(196ba4ff)

$surface = rgba(101417ff)

$surface_bright = rgba(36393eff)

$surface_container = rgba(1d2024ff)

$surface_container_high = rgba(272a2eff)

$surface_container_highest = rgba(323539ff)

$surface_container_low = rgba(191c20ff)

$surface_container_lowest = rgba(0b0e12ff)

$surface_dim = rgba(101417ff)

$surface_tint = rgba(97cbffff)

$surface_variant = rgba(414750ff)

$tertiary = rgba(edb1ffff)

$tertiary_container = rgba(865298ff)

$tertiary_fixed = rgba(f9d8ffff)

$tertiary_fixed_dim = rgba(edb1ffff)

