background #010410
foreground #ffc6ff
cursor #ffc6ff
border #ffc6ff
selection_foreground  #c4c6cf
selection_background  #43474e

url_color               #af88ff

color0 #010410
color8   #061143

color1   #9f36f8
color9   #7d51a4

color2   #a33aff
color10  #8457b7

color3   #ff37d8
color11  #be529b

color4   #af88ff
color12  #8f70ed

color5   #9f98ff
color13  #8480f4

color6   #ff90fd
color14  #f965c5

color7   #ffffff
color15  #ffc6ff
