# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#010410\033\\"
printf "\033]4;1;#9f36f8\033\\"
printf "\033]4;2;#a33aff\033\\"
printf "\033]4;3;#ff37d8\033\\"
printf "\033]4;4;#af88ff\033\\"
printf "\033]4;5;#9f98ff\033\\"
printf "\033]4;6;#ff90fd\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#061143\033\\"
printf "\033]4;9;#7d51a4\033\\"
printf "\033]4;10;#8457b7\033\\"
printf "\033]4;11;#be529b\033\\"
printf "\033]4;12;#8f70ed\033\\"
printf "\033]4;13;#8480f4\033\\"
printf "\033]4;14;#f965c5\033\\"
printf "\033]4;15;#ffc6ff\033\\"

# Background
printf "\033]11;#010410\033\\";

# Foreground
printf "\033]10;#ffc6ff\033\\";

# Cursor
printf "\033]12;#ffc6ff\033\\";

# Border
printf "\033]7044;#ffc6ff\033\\";
