# Generated by hellwal

wallpaper='/home/n0ctanedev/Pictures/wallpaper.png'

background='010410'
foreground='ffc6ff'
cursor='ffc6ff'
border='ffc6ff'

color0='010410'
color1='9f36f8'
color2='a33aff'
color3='ff37d8'
color4='af88ff'
color5='9f98ff'
color6='ff90fd'
color7='ffffff'
color8='061143'
color9='7d51a4'
color10='8457b7'
color11='be529b'
color12='8f70ed'
color13='8480f4'
color14='f965c5'
color15='ffc6ff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
