// this file is automatically generated..
// by the N0ctConfig system using the config...
//  ~/.config/N0ctBar/config.jsonc

export const dash_Scale = 1.0;
export const dash_Font_Size = 12;
export const dash_Margin = 8;
export const pfp_Url = "~/.face"; 